version: '3.1'
networks:
  backend:

services:
  nginx:
    image: nginx:stable
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "5001:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - backend

  mariadb:
    image: mariadb:latest
    container_name: laravel-mariadb
    restart: unless-stopped
    environment:
     MYSQL_ROOT_PASSWORD: 12345678
     MYSQL_USER: laravel
     MYSQL_PASSWORD: 12345678
     MYSQL_DATABASE: ldb
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql:rw
    networks:
      - backend

  adminer:
    image: adminer
    container_name: laravel-mariadb-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    networks:
      - backend

  composer:
      image: composer:2.2.6
      container_name: laravel-composer
      volumes:
        - ./src:/var/www/html
      depends_on:
        - php
      networks:
        - backend

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - mariadb
      - nginx
    working_dir: /var/www/html
    entrypoint: ["php","/var/www/html/artisan"]
    networks:
      - backend
